version: "2"
networks:
  test:
services:
  couchdb_peer1_org1_example_com:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7052:5984
    container_name: couchdb_peer1_org1_example_com
    networks:
      - test
  couchdb_peer1_org2_example_com:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 9052:5984
    container_name: couchdb_peer1_org2_example_com
    networks:
      - test
  couchdb_peer2_org1_example_com:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7152:5984
    container_name: couchdb_peer2_org1_example_com
    networks:
      - test
  couchdb_peer2_org2_example_com:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 9152:5984
    container_name: couchdb_peer2_org2_example_com
    networks:
      - test
  couchdb_peer3_org1_example_com:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7252:5984
    container_name: couchdb_peer3_org1_example_com
    networks:
      - test
  couchdb_peer3_org2_example_com:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 9252:5984
    container_name: couchdb_peer3_org2_example_com
    networks:
      - test
  peer1_org1_example_com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_peer1_org1_example_com:5984
    depends_on:
      - couchdb_peer1_org1_example_com
  peer1_org2_example_com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_peer1_org2_example_com:5984
    depends_on:
      - couchdb_peer1_org2_example_com
  peer2_org1_example_com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_peer2_org1_example_com:5984
    depends_on:
      - couchdb_peer2_org1_example_com
  peer2_org2_example_com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_peer2_org2_example_com:5984
    depends_on:
      - couchdb_peer2_org2_example_com
  peer3_org1_example_com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_peer3_org1_example_com:5984
    depends_on:
      - couchdb_peer3_org1_example_com
  peer3_org2_example_com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_peer3_org2_example_com:5984
    depends_on:
      - couchdb_peer3_org2_example_com
