Organizations:
  - Name: org1
    ID: org1
    MSPDir: ../organizations/peerOrganizations/org1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: OR('org1.admin', 'org1.peer', 'org1.client')
      Writers:
        Type: Signature
        Rule: OR('org1.admin', 'org1.client')
      Admins:
        Type: Signature
        Rule: OR('org1.admin')
      Endorsement:
        Type: Signature
        Rule: OR('org1.peer')
  - Name: orderOrg
    ID: orderOrg
    MSPDir: ../organizations/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: OR('orderOrg.member')
      Writers:
        Type: Signature
        Rule: OR('orderOrg.member')
      Admins:
        Type: Signature
        Rule: OR('orderOrg.admin')
    OrdererEndpoints:
      - orderer.example.com:7050
Capabilities:
  Channel:
    V2_0: true
  Orderer:
    V2_0: true
  Application:
    V2_0: true
Application:
  Organizations:
    - {}
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    Endorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: ANY Endorsement
  Capabilities:
    V2_0: true
Orderer:
  OrdererType: etcdraft
  Addresses:
    - orderer.example.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.example.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 500
    AbsoluteMaxBytes: 10MB
    PreferredMaxBytes: 2KB
  Organizations:
    - ""
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    BlockValidation:
      Type: ImplicitMeta
      Rule: ANY Writers
Channel:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
  Capabilities:
    V2_0: true
Profiles:
  OrdererGenesis:
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Capabilities:
      V2_0: true
    Orderer:
      OrdererType: etcdraft
      Addresses:
        - orderer.example.com:7050
      EtcdRaft:
        Consenters:
          - Host: orderer.example.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 500
        AbsoluteMaxBytes: 10MB
        PreferredMaxBytes: 2KB
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        BlockValidation:
          Type: ImplicitMeta
          Rule: ANY Writers
      Organizations:
        - Name: orderOrg
          ID: orderOrg
          MSPDir: ../organizations/ordererOrganizations/example.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('orderOrg.member')
            Writers:
              Type: Signature
              Rule: OR('orderOrg.member')
            Admins:
              Type: Signature
              Rule: OR('orderOrg.admin')
          OrdererEndpoints:
            - orderer.example.com:7050
      Capabilities:
        V2_0: true
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: org1
            ID: org1
            MSPDir: ../organizations/peerOrganizations/org1.example.com/msp
            Policies:
              Readers:
                Type: Signature
                Rule: OR('org1.admin', 'org1.peer', 'org1.client')
              Writers:
                Type: Signature
                Rule: OR('org1.admin', 'org1.client')
              Admins:
                Type: Signature
                Rule: OR('org1.admin')
              Endorsement:
                Type: Signature
                Rule: OR('org1.peer')
  OrgsChannel:
    Consortium: SampleConsortium
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Capabilities:
      V2_0: true
    Application:
      Organizations:
        - Name: org1
          ID: org1
          MSPDir: ../organizations/peerOrganizations/org1.example.com/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR('org1.admin', 'org1.peer', 'org1.client')
            Writers:
              Type: Signature
              Rule: OR('org1.admin', 'org1.client')
            Admins:
              Type: Signature
              Rule: OR('org1.admin')
            Endorsement:
              Type: Signature
              Rule: OR('org1.peer')
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        Endorsement:
          Type: ImplicitMeta
          Rule: MAJORITY Endorsement
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: ANY Endorsement
      Capabilities:
        V2_0: true
